### ISSUE TITLE
HttpMethods missing PATCH

### ISSUE THREAD

**Issue by richardhundt** [gimlet2/kottpd#7]
There seems to be no support for PATCH.

**Comment by gimlet2** [comment]
Thanks! Please check release 0.1.3 with PATCH support https://github.com/gimlet2/kottpd/releases/tag/0.1.3.
There is no patch specific api method but you could use `bind(HttpMethod.PATCH, path, call)`

**Comment by richardhundt** [comment]
Good to know, thanks!
